# Generated by Django 2.2 on 2019-04-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0003_facebookuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('following', models.ManyToManyField(related_name='followers', to='many_to_many.InstagramUser')),
            ],
        ),
    ]
