# Generated by Django 2.2 on 2019-04-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('age1', models.IntegerField(blank=True)),
                ('age2', models.IntegerField(null=True)),
                ('age3', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
