# Generated by Django 2.2 on 2019-04-10 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_table', '0002_restaurant1_old_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant1',
            name='place_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multi_table.Place1'),
        ),
    ]
