# Generated by Django 2.2 on 2019-04-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0005_auto_20190408_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='relation_users',
            field=models.ManyToManyField(related_name='_twitteruser_relation_users_+', through='many_to_many.Relation', to='many_to_many.TwitterUser'),
        ),
    ]
